adds getfullpath overload
System-IO-Abstractions/System.IO.Abstractions pull request #657
Opened 2020-10-14 10:27 UTC by Ibrahim-Islam

#654

2020-10-14 11:56 UTC, fgreinacher requested changes
Thanks a lot! Let's use the feature-based constants for consistency

2020-10-14 11:56 UTC, fgreinacher commented on src/System.IO.Abstractions/IPath.cs
> +#if NETSTANDARD2_1
```suggestion
#if FEATURE_ADVANCED_PATH_OPERATIONS
```

2020-10-14 11:56 UTC, fgreinacher commented on src/System.IO.Abstractions/PathBase.cs
> +#if NETSTANDARD2_1
```suggestion
#if FEATURE_ADVANCED_PATH_OPERATIONS
```

2020-10-14 11:56 UTC, fgreinacher commented on src/System.IO.Abstractions/PathWrapper.cs
> +# if NETSTANDARD2_1
```suggestion
#if FEATURE_ADVANCED_PATH_OPERATIONS
```

2020-10-15 04:45 UTC, Ibrahim-Islam commented
Would also really appreciate if you can label this pr `hacktoberfest-accepted`

2020-10-15 10:14 UTC, merged

2020-10-15 10:15 UTC, fgreinacher commented
Sure, thanks a lot!