Add PackageIcon for nuget
System-IO-Abstractions/System.IO.Abstractions pull request #742
Opened 2021-07-20 13:39 UTC by soi013

It would be better to have an icon when searching for nuget.

![image](https://user-images.githubusercontent.com/23096880/126333841-ef380cdf-2fd8-4251-a336-b48a409eb6a4.png)

2021-07-23 08:53 UTC, fgreinacher requested changes

2021-07-23 08:53 UTC, fgreinacher commented on src/System.IO.Abstractions.TestingHelpers/System.IO.Abstractions.TestingHelpers.csproj
> +        <PackageIconUrl>https://avatars1.githubusercontent.com/u/40829877</PackageIconUrl>
This property seems to be obsolete [according to the build log](https://github.com/System-IO-Abstractions/System.IO.Abstractions/pull/742/checks?check_run_id=3141881403#step:4:23). Could you change this to follow current guidelines?

2021-07-23 22:25 UTC, soi013 commented
OK. I will change it in two days after tomorrow.

2021-07-26 16:59 UTC, soi013 commented
Can I add the icon in the solution folder?
ex) /System.IO.Abstractions/System.IO.Abstractions_Icon_256x256.png

https://avatars1.githubusercontent.com/u/40829877

Is this logo image copyrighted by the System.IO.Abstractions project?

Because, PackageIcon needs folder-based source.

https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#packageicon
> Visual Studio supports PackageIcon for packages coming from a folder-based source.

2021-07-26 17:44 UTC, fgreinacher commented
Thanks for driving this forward!

> Can I add the icon in the solution folder?
> ex) /System.IO.Abstractions/System.IO.Abstractions_Icon_256x256.png

Yes, please put it to `./images/icon_256x256.png`.

> Is this logo image copyrighted by the System.IO.Abstractions project?

Yes, it's from the [Arabia IO pack](https://www.shareicon.net/pack/arabia-io) that is free for personal use (see https://github.com/System-IO-Abstractions/System.IO.Abstractions/issues/324).

2021-07-27 20:10 UTC, fgreinacher commented
Thanks a lot 👍

2021-07-27 20:11 UTC, merged